#!/bin/sh
if [ ! -f $HOME/.zsh_history ]; then
    echo "File not found!"
    return
fi
echo "Preparing to clear zsh history"

DATE=`date '+%Y-%m-%d-%H:%M'`
FILE=$HOME/zsh-history-backup-$DATE.txt

cat $HOME/.zsh_history > $FILE
cat /dev/null > $HOME/.zsh_history
echo Saved as $FILE



