#!/usr/bin/env python3

import requests
import json

r = requests.get("https://ion.tjhsst.edu/api/schedule?format=json")

js = json.loads(r.text)
schedule = js["results"][0]["day_type"]["blocks"]
for block in schedule:
    print(block["name"], block["start"], block["end"])
